<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>a059067b25bd65205ee5d32e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-06-14 10:40:28</createtime><buildsignature>Local.Unknown.Unknown.1.63.134.1020-1.200.000.452.Release</buildsignature><categoryid>season_service.py:583</categoryid><desyncid>a059067b25bd65205ee5d32e</desyncid><systemconfig/><screenshot/><desyncdata>Exception in &lt;function c_api_server_tick at 0x00007FF4E3486CB0&gt;, args: (243762028390,), kwargs: {}&#13;&#10;AttributeError("'NoneType' object has no attribute 'on_season_set'") (AttributeError: 'NoneType' object has no attribute 'on_season_set')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\seasons\season_service.py", line 583, in _update_season_aware_objects_gen [&#13;&#10;                   self : season_service,&#13;&#10;               timeline : &lt;scheduling.Timeline object at 0x00007FF4900D6B10&gt;,&#13;&#10;    season_aware_object : collectibles_spawnerObject_LeafPile:0x0000000000000000]&#13;&#10;AttributeError: 'NoneType' object has no attribute 'on_season_set'rtim=0&#13;&#10;Client Session Time: 38.84&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: Intel(R) HD Graphics igdumd64.dll 9.17.10.4459, GUID: D7B78E66-4246-11CF-9862-CD33B7C2C435&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>a059067b25bd65205ee5d32e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-06-14 16:55:07</createtime><buildsignature>Local.Unknown.Unknown.1.63.134.1020-1.200.000.452.Release</buildsignature><categoryid>transition_sequence.py:4127</categoryid><desyncid>a059067b25bd65205ee5d32e</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: Sim  failed to find carry posture aop for carry target object_foodPlatter:0x0000000000000000.)&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 4054, in run_transition_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 3676, in create_transition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 4136, in create_posture_state_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 4127, in _create_posture_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture_state.py", line 159, in __init__RuntimeError: Sim  failed to find carry posture aop for carry target object_foodPlatter:0x0000000000000000.rtim=0&#13;&#10;Client Session Time: 38.84&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: Intel(R) HD Graphics igdumd64.dll 9.17.10.4459, GUID: D7B78E66-4246-11CF-9862-CD33B7C2C435&#13; &#10;</desyncdata></report>
</root>